DB設計の作成
JunkiKikuchi/chat-space pull request #1
Opened 2019-03-10 09:23 UTC by JunkiKikuchi

# What
ChatSpaceの実装をするため、DB設計を行う。

# Why
各機能実装に必須となるため。

2019-03-24 11:22 UTC, yuki-uchida requested changes

2019-03-24 11:22 UTC, yuki-uchida commented on README.md
> +|id|integer|primary key, index: true|
全てのテーブルでidは書かなくていいです

2019-03-24 11:22 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
外部キーの場合にはrefference型としましょう

2019-03-24 11:22 UTC, yuki-uchida commented on README.md
> +|image|string|null: true, default: null|
画像かテキストのどちらかがあれば、投稿できるようにしましょう

2019-03-24 13:04 UTC, JunkiKikuchi commented
以下、修正しました。
・usersテーブル、groupsテーブル、messagesテーブルからidカラムを削除
・membersテーブル、messagesテーブルのgroup_idカラム、user_idカラムを
　integer型からreference型へ変更
・messagesテーブルのmessageカラムへバリデーションを追加
　(messageカラムがnullの時、imageカラムがnullではないことのチェック)

2019-03-25 01:44 UTC, miyagit commented on README.md
> +### Association
メッセージのアソシエーションも追加しましょう。

2019-03-25 15:52 UTC, JunkiKikuchi commented
groupsテーブルとmessagesテーブルのアソシエーションを追加しました。

2019-03-26 02:05 UTC, TOMARUMARU commented on README.md
> +|image|string|null: true, default: null|
こちら修正されていません

2019-03-26 02:06 UTC, TOMARUMARU requested changes
指摘を受けた箇所で修正されていないところがあります

2019-03-26 12:35 UTC, JunkiKikuchi commented
「修正されていないところがある」との指摘ですが、
以前指摘いただいた「画像かテキストのどちらかがあれば、投稿できるようにする」という部分かと思います。
この部分については、messagesテーブルのアソシエーションに
validates message, presence: true, unless: :image? を追加しているのですが、この対応だけだと不十分と
言うことでしょうか。

2019-03-26 12:41 UTC, JunkiKikuchi commented on README.md
> +|image|string|null: true, default: null|
「修正されていないところがある」との指摘ですが、
以前指摘いただいた「画像かテキストのどちらかがあれば、投稿できるようにする」
という部分のことかと思います。
この部分については、messagesテーブルのアソシエーションに
validates message, presence: true, unless: :image? を追加しているのですが、この対応だけでは不十分と言うことでしょうか。

2019-03-26 12:45 UTC, TOMARUMARU commented on README.md
> +|image|string|null: true, default: null|
null: trueと記述されていたのですね。失礼いたしました、null: falseと勘違いしていました。
nullの許容はdefaultの設定なので、記述しなくて大丈夫です

2019-03-26 12:45 UTC, TOMARUMARU commented on README.md
> +- validates message, presence: true, unless: :image?
validationはDBとは関係ないので、こちらの記述は消していただいて大丈夫です

2019-03-26 12:52 UTC, JunkiKikuchi commented on README.md
> +|image|string|null: true, default: null|
messagesテーブルのmessageおよびimageからnullのdefault設定を削除しました。

2019-03-26 12:53 UTC, JunkiKikuchi commented on README.md
> +- validates message, presence: true, unless: :image?
messagesテーブルのアソシエーションからvalidatesの記述を削除しました。

2019-03-26 12:57 UTC, TOMARUMARU approved these changes
LGTM

2019-03-26 12:59 UTC, merged